### ISSUE TITLE
Optical & Acoustic Property Literature Research

### ISSUE THREAD

**Issue by mschllnbrg** [CAMI-DKFZ/simpa#41]
Look up the literature values of optical and acoustic properties of the tissue classes and molecule classes.

Optical properties:
- mua (at 700, 800, and 900 nm)
- mus (at 500 nm)
- anisotropy

Acoustic properties:
- density
- speed of sound
- alpha coefficient

Please collect the info in one file (preferably nicely structured :-)) and don't forget to include the references.

**Comment by kdreher** [comment]
I think we can concentrate on the optical properties since the [IT’IS Database for thermal and electromagnetic parameters of biological tissues](https://itis.swiss/virtual-population/tissue-properties/downloads/database-v4-0/) is already included in [literature_values.py ](https://github.com/CAMI-DKFZ/simpa/blob/develop/simpa/utils/libraries/literature_values.py).
However, a quick check by someone that all the values were transferred correctly can not hurt :)
