### ISSUE TITLE
Implement DMAS and sDMAS in Python

### ISSUE THREAD

**Issue by jgroehl** [CAMI-DKFZ/simpa#44]
- [x] DMAS
- [x] sDMAS

**Comment by TomTomRixRix** [comment]
A first version is implemented, see results displayed below. However, due to memory constraints the outer loop over the x-dimension wasn't vectorized, which leads to longer computation times (2-20s). This problem is related to #32.

![grafik](https://user-images.githubusercontent.com/13121269/115879786-54ab9c00-a44a-11eb-9b87-5d884df86f35.png)

**Comment by TomTomRixRix** [comment]
Now simulation tests as well as tests for the convenience reconstruction functions exist.

**Comment by jgroehl** [comment]
Images are looking really good 👍

**Comment by jgroehl** [comment]
Integrated code to work with the new code base and refactored the test methods to reduce the amount of duplicate code.
Merged into #57. Closing.
