### ISSUE TITLE
Adaptation of scattering values in MCX adapter 

### ISSUE THREAD

**Issue by mschllnbrg** [CAMI-DKFZ/simpa#55]
Since MCX requires an anisotropy value of g=0.9, we need to adjust the scattering values accordingly.

**Comment by jgroehl** [comment]
To clarify: in the current version, when using heterogeneous voxelised maps of absorption and scattering, mcx expects a single floating point value as the anisotropy.
In order to accommodate this, we need to recalculate the scattering coefficient map accordingly in order to simulate with the correct reduced scattering coefficient.

**Comment by jgroehl** [comment]
Is integrated into #40.
At some point, we definitely want to correctly use the anisotropy in the simulation, though..
